#!/usr/bin/env python3
"""
Test script to validate AI analysis improvements:
1. Optimized prompt (simpler language, structured output)
2. Fast response with concise text
3. Download report generation
4. UI stability with fixed height container
"""

import os
import json
import sys
from google import genai

def test_optimized_prompt():
    """Test that the optimized prompt generates simple, structured output"""
    
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("❌ GEMINI_API_KEY not set")
        return False
    
    client = genai.Client(api_key=api_key)
    model = "gemini-2.5-flash"
    
    # Use the optimized prompt from app.py
    port = 22
    service = "SSH"
    banner = "OpenSSH_7.4"
    severity = "HIGH"
    
    prompt = f"""Analyze this port scan result in SIMPLE words for non-technical users:

Port: {port}
Service: {service}
Banner: {banner}
Risk: {severity}

Provide ONLY:
1. What is this port? (1-2 lines, simple language)
2. Why is it risky? (2-3 key points as bullets)
3. How to secure it? (3-4 quick fixes as bullets)
4. Risk score: LOW/MEDIUM/HIGH/CRITICAL

Use SHORT sentences. NO technical jargon. Focus on practical actions.
Keep total response under 200 words."""

    try:
        print("🔄 Testing optimized prompt...")
        print(f"   Model: {model}")
        print(f"   Port: {port}/{service}")
        print()
        
        response = client.models.generate_content(
            model=model,
            contents=prompt
        )
        
        analysis = response.text
        
        # Check response quality
        checks = {
            "Contains 'What is'": "What is" in analysis or "what is" in analysis,
            "Contains 'Why' or 'Risk'": "Why" in analysis or "risk" in analysis.lower(),
            "Contains 'How to secure'": "How" in analysis or "secure" in analysis.lower(),
            "Contains 'Risk score'": "Risk" in analysis or "CRITICAL" in analysis or "HIGH" in analysis,
            "Under 300 words": len(analysis.split()) < 300,
        }
        
        print("✅ AI Analysis Generated")
        print("-" * 70)
        print(analysis)
        print("-" * 70)
        print()
        print("📊 Quality Checks:")
        for check, passed in checks.items():
            status = "✓" if passed else "✗"
            print(f"  {status} {check}")
        
        all_passed = all(checks.values())
        if all_passed:
            print()
            print("✅ All checks passed! Optimized prompt is working well.")
        return all_passed
        
    except Exception as e:
        print(f"❌ Error: {e}")
        return False


def test_response_speed():
    """Test that response is fast (under 5 seconds)"""
    import time
    
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("❌ GEMINI_API_KEY not set")
        return False
    
    client = genai.Client(api_key=api_key)
    
    prompt = "Explain DNS briefly in 50 words for non-technical users."
    
    try:
        print("⏱️  Testing response speed...")
        start = time.time()
        
        response = client.models.generate_content(
            model="gemini-2.5-flash",
            contents=prompt
        )
        
        elapsed = time.time() - start
        
        print(f"   Response time: {elapsed:.2f}s")
        print(f"   Word count: {len(response.text.split())}")
        
        if elapsed < 5:
            print("✅ Response is fast (< 5s)")
            return True
        else:
            print(f"⚠️  Response took {elapsed:.2f}s (consider optimizing)")
            return False
            
    except Exception as e:
        print(f"❌ Error: {e}")
        return False


def test_report_generation():
    """Test that report download endpoint would work"""
    print("📄 Testing report generation capabilities...")
    
    try:
        from reportlab.lib.pagesizes import letter
        from reportlab.platypus import SimpleDocTemplate
        print("   ✓ reportlab available (PDF generation ready)")
        
        # Test TXT fallback
        sample_text = "This is test analysis.\nPort 22 is SSH.\nClose unused ports."
        formatted = f"""================================================================================
VulnX SECURITY ANALYSIS REPORT
================================================================================

SCAN DETAILS:
Port: 22
Service: SSH
Generated: 2026-02-25 10:30:00
Tool: VulnX AI Scanner

================================================================================
AI ANALYSIS:
================================================================================

{sample_text}

================================================================================
Report generated by VulnX AI Security Scanner | Powered by Google Gemini
================================================================================"""
        
        print("   ✓ TXT fallback ready")
        print()
        print("✅ Report generation is ready")
        return True
        
    except ImportError:
        print("   ⚠️  reportlab not available (TXT fallback will be used)")
        return True
    except Exception as e:
        print(f"❌ Error: {e}")
        return False


def main():
    print()
    print("=" * 70)
    print("VulnX AI IMPROVEMENTS TEST SUITE")
    print("=" * 70)
    print()
    
    tests = [
        ("Optimized Prompt", test_optimized_prompt),
        ("Response Speed", test_response_speed),
        ("Report Generation", test_report_generation),
    ]
    
    results = {}
    for name, test_func in tests:
        print(f"\n[{name}]")
        print("-" * 70)
        results[name] = test_func()
        print()
    
    print("=" * 70)
    print("TEST SUMMARY")
    print("=" * 70)
    
    for name, passed in results.items():
        status = "✅ PASS" if passed else "❌ FAIL"
        print(f"{status}: {name}")
    
    all_passed = all(results.values())
    print()
    if all_passed:
        print("🎉 All tests passed! AI improvements are ready for production.")
    else:
        print("⚠️  Some tests failed. Check the output above for details.")
    
    return 0 if all_passed else 1


if __name__ == "__main__":
    sys.exit(main())
